# Set CMake flags to build for RP2350
# Modified from here: https://github.com/joachimBurket/esp32-opencv/blob/master/esp32/doc/detailed_build_procedure.md
CMAKE_ARGS += -DCMAKE_BUILD_TYPE=Release
CMAKE_ARGS += -DBUILD_SHARED_LIBS=OFF
CMAKE_ARGS += -DCV_DISABLE_OPTIMIZATION=OFF
CMAKE_ARGS += -DWITH_IPP=OFF
CMAKE_ARGS += -DWITH_TBB=OFF
CMAKE_ARGS += -DWITH_OPENMP=OFF
CMAKE_ARGS += -DWITH_PTHREADS_PF=OFF
CMAKE_ARGS += -DWITH_QUIRC=OFF
CMAKE_ARGS += -DWITH_1394=OFF
CMAKE_ARGS += -DWITH_CUDA=OFF
CMAKE_ARGS += -DWITH_OPENCL=OFF
CMAKE_ARGS += -DWITH_OPENCLAMDFFT=OFF
CMAKE_ARGS += -DWITH_OPENCLAMDBLAS=OFF
CMAKE_ARGS += -DWITH_VA_INTEL=OFF
CMAKE_ARGS += -DWITH_EIGEN=OFF

CMAKE_ARGS += -DWITH_GSTREAMER=OFF
CMAKE_ARGS += -DWITH_GTK=OFF
CMAKE_ARGS += -DWITH_JASPER=OFF
CMAKE_ARGS += -DWITH_JPEG=OFF
CMAKE_ARGS += -DWITH_WEBP=OFF
CMAKE_ARGS += -DBUILD_ZLIB=OFF
CMAKE_ARGS += -DBUILD_PNG=OFF
CMAKE_ARGS += -DWITH_TIFF=OFF
CMAKE_ARGS += -DWITH_V4L=OFF
CMAKE_ARGS += -DWITH_LAPACK=OFF
CMAKE_ARGS += -DWITH_ITT=OFF
CMAKE_ARGS += -DWITH_PROTOBUF=OFF
CMAKE_ARGS += -DWITH_IMGCODEC_HDR=OFF
CMAKE_ARGS += -DWITH_IMGCODEC_SUNRASTER=OFF
CMAKE_ARGS += -DWITH_IMGCODEC_PXM=OFF
CMAKE_ARGS += -DWITH_IMGCODEC_PFM=OFF

CMAKE_ARGS += -DBUILD_LIST=core,imgproc,imgcodecs
CMAKE_ARGS += -DBUILD_JAVA=OFF
CMAKE_ARGS += -DBUILD_opencv_python=ON
CMAKE_ARGS += -DBUILD_opencv_java=OFF

CMAKE_ARGS += -DBUILD_opencv_apps=OFF
CMAKE_ARGS += -DBUILD_PACKAGE=OFF
CMAKE_ARGS += -DBUILD_PERF_TESTS=OFF
CMAKE_ARGS += -DBUILD_TESTS=OFF
CMAKE_ARGS += -DCV_ENABLE_INTRINSICS=OFF
CMAKE_ARGS += -DCV_TRACE=OFF
CMAKE_ARGS += -DOPENCV_ENABLE_MEMALIGN=OFF

CMAKE_ARGS += -DCMAKE_TOOLCHAIN_FILE=~/micropython-opencv/micropython/lib/pico-sdk/cmake/preload/toolchains/pico_arm_cortex_m33_gcc.cmake
CMAKE_ARGS += -DOPENCV_DISABLE_THREAD_SUPPORT=ON

# Build OpenCV
all:
	mkdir -p build && cd build && cmake -S .. -B . -DPICO_BUILD_DOCS=0 ${CMAKE_ARGS} && make -f Makefile $(MAKEFLAGS) $(MAKE_ARGS)

# Clean the OpenCV build
clean:
	rm -rf build
